### PR TITLE
fix unable to find non-public method of super class

### PR DESCRIPTION
**Pull request by zuoc**
### Does this pull request fix one issue?

 #96 fix unable to find non-public method of super class

### CODE REVIEW

**Comment by xcaspar** [comment]
@zuoc Thank you for your contribution. Your email or name of git config may be incorrect , please check it, then I will merge the pr.

**Comment by zuoc** [comment]
I added my email, please try again.

**Comment by xcaspar** [comment]
> I added my email, please try again.

Sorry it's incorrect yet, you can execute the follow commands to resolve it:
```
# for example your github name is zuoc and your github email is max.zuoc@outlook.com, this command will change the HEAD commit, then you force push it to remote.

git commit --amend --author "zuoc <max.zuoc@outlook.com>"
```

**Comment by zuoc** [comment]
i done

**Pull request merged**
