### PR TITLE
feature: add business data match

### LINKED ISSUE #203: Add business data match Injection
## Issue Description

Type:  *feature request*

### Describe  what feature you want
&emsp;&emsp; Chaosblade-exec-jvm already supports coarse-grained explosion radius control, such as Dubbo Group, Version, which is generally sufficient for single-application drills.
&emsp;&emsp;  At Qunar.com, we hope to be able to randomly drill all online businesses under this requirement. More precise explosion radius control is needed, for example, all the weakly dependent interfaces involved in a certain interface at the app entrance are drilled. These interfaces may be distributed across hundreds of applications at different levels downstream.
&emsp;&emsp;1. How can we ensure that the injection of faults in hundreds of applications will not affect the business of other calling applications, which is the basis for the drill..
&emsp;&emsp;2. How to do the same as automatic Stress Testing. When injecting faults, we can gradually increase the user impact from the smallest scale to the full scale.
&emsp;&emsp; Based on this, we hope to achieve the above effects by matching fault injection with distributed link tracing or other transmitted business data. It is hoped that this solution does not rely on specific link tracking middleware, such as Hawk-eye and QTRACE (Qunar.com distributed link tracking).
&emsp;&emsp;目前chaosblade-exec-jvm已经支持了粗粒度的爆炸半径控制，比如dubbo，group、version，这在单应用的演练中一般是够用的。
&emsp;&emsp;在去哪网，我们希望可以做到对线上所有的业务可以随机演练，这个要求下。就需要更精准的爆炸半径控制，比如对app入口某个接口下的所有涉及到的弱依赖接口都进行演练。这些接口可能分布在下游不同层级的上百个应用中。
&emsp;&emsp;1.我们怎么保障在为这上百个注入故障的同时，不影响其它调用应用的业务，是演练可以进行的基础。
&emsp;&emsp;2.怎么做到像自动化压测式的自动加压一样。我们在注入故障的时候可以从最小规模的用户影响，逐渐增大到全量。
&emsp;&emsp;基于此我们希望可以借助分布式链路追踪或其它方式传递的业务数据进行故障注入的匹配，来达到以上效果。并且希望此解决方案不依赖于具体的链路追踪中间件，如鹰眼、QTRACE（去哪网分布式链路追踪）。

### Describe what you expected to happen?
&emsp;&emsp;1. Obtain the business data passed in trace by Dubbo, HTTP and other RPC calling clients or  get data by implement the  for matching injection.
&emsp;&emsp;通过在dubbo、http 等rpc调用客户端中获取trace中传递的业务数据或者通过spi实现业务数据获取，进行匹配注入。
&emsp;&emsp;2. RPC calls support custom retrieval of business data through jsonPath from HTTP headers or map  returned in getAttachments of Dubbo Invocationd.
&emsp;&emsp; rpc方式支持在dubbo  invocationd的getAttachments中返回的map或http header通过jsonpath定制化获取业务数据。
&emsp;&emsp;3. Spi obtains business data by implementing the following interfaces

&emsp;&emsp; spi 方式通过实现以下接口获取业务数据
                            public interface BusinessDataGetter {
                                     String get(String key) throws Exception;
                            }
                         

	--b-parms='[{
		"key":"a1.b1.b1",
		"value":"a_value"，
                “mode”:"rpc"
	},
	{
		"key":"a2.b2.c2",
		"value":"b_value",
                 “mode”:"spi"
	}]’

#### http example：
    blade create http throwCustomException --uri='https://www.baidu.com'
    --b-parms='[{
		"key":"a1.b1.c1",
		"value":"a_value",
                 “mode”:"rpc"
	},
	{
		"key":"a2.b2.c2",
		"value":"b_value",
                 “mode”:"rpc"
	}]’
**Injection  Conditon Expressed By Java Codes:**

       JSON.parseObject(header.get("a1")) .getString("b1.c1").equals(a_value)
      &&
      JSON.parseObject(header.get("a2")) .getString("b2.c2").equals(b_value)
#### dubbo example：
    blade create dubbo throwCustomException --consumer --service=com.qunar.api --version=1.0.0  --b-parms='[{
		"key":"a",
		"value":"a_value",
                 “mode”:"spi"
	},
	{
		"key":"b",
		"value":"b_value",
                 “mode”:"spi"
	}]’
**Injection  Conditon Expressed By Java Codes:**

       BusinessDataGetter.get("a").equals(a_value)
      &&
       BusinessDataGetter.get("b").equals(b_value)

### PR DESCRIPTION
**Pull request by wufunc**
Signed-off-by: wufan <wufunc@gmail.com>

### Describe what this PR does / why we need it
        Provides the ability to match specific business data for injection by getting business data from rpc or implementing the specific spi interface.

### Does this pull request fix one issue?

       Fixes #203
### Describe how you did it
    blade create dubbo throwCustomException --consumer --service=com.qunar.api --version=1.0.0  --b-parms='[{
    "key":"a",
    "value":"a_value",
    “mode”:"spi"
    },
    {
    "key":"b",
    "value":"b_value",
    “mode”:"spi"
    }]’

### CODE REVIEW

**Review by xcaspar — APPROVED** [review]

**Comment by xcaspar** [comment]
#204

**Comment by hooq77** [comment]
请问下，如果我不想使用b-params匹配，我应该怎么传值呢？

**Comment by sanxun0325** [comment]
那就--b-parms 整体都不传

**Comment by hooq77** [comment]
不行，会提示illegal json

**Comment by sanxun0325** [comment]
你用的版本不对吧，使用1.4.0以上

**Pull request merged**
